## Lecture 3.2 - Numpy in Python

In [2]:
import numpy as np

arr = np.array([1,2,5,4,9,8,6])

print(arr)

print(type(arr))

[1 2 5 4 9 8 6]
<class 'numpy.ndarray'>


In [3]:
arr = np.arange(1,9,2)

print(arr)

[1 3 5 7]


In [6]:
arr = np.zeros(5, int)

print(arr)

[0 0 0 0 0]


In [9]:
arr = np.zeros([4,3])

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr = np.diag([2,3,5,7])

print(arr)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


## Random Generation in Numpy

In [14]:
arr = np.random.rand(5)

print(arr)

[0.46415074 0.31504175 0.26791122 0.12049818 0.57031656]


In [16]:
arr = np.random.randint(0, 10, 10)

print(arr)

[1 2 0 2 1 8 7 9 2 1]


In [17]:
n = arr.max()

print(n)

9


In [18]:
arr = np.random.randint(0,100,15)

print(arr)

[33 78 59 51 19 23 34 14 94 95 20 91 15 93 95]


In [19]:
print(arr[5])

23


In [20]:
print(arr[2:6])

[59 51 19 23]


In [21]:
print(arr[:7])

[33 78 59 51 19 23 34]


In [22]:
print(arr[:])

[33 78 59 51 19 23 34 14 94 95 20 91 15 93 95]


In [23]:
arr2d = np.random.randint(0,100,(5,5))

print(arr2d)

[[32  4 17 64 18]
 [37 17 10 64 71]
 [84 13 76 69 62]
 [39 14 95 68 28]
 [ 8  6 40 11 32]]


In [25]:
print(arr2d[1],[2])

[37 17 10 64 71] [2]


In [26]:
print(arr[1,2])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [28]:
arr = np.arange(12).reshape(4,3)

print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
print(arr[3][1])

10


In [30]:
print(arr[1][1])

4


In [31]:
print(arr[0:2, 0:2])

[[0 1]
 [3 4]]


In [32]:
print(arr[1:4, 1:3])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [33]:
arr = np.arange(1,13)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
print(arr+arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [37]:
arr1 = np.arange(1,15)

print(arr+arr1)

ValueError: operands could not be broadcast together with shapes (12,) (14,) 

In [38]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr1)

[[1 2 3]
 [4 5 6]]


In [39]:
print(arr1.dtype)

int32


In [42]:
print(arr1.ndim)

2


In [41]:
print(arr1.size)

6
